# Generated by Django 3.0.6 on 2021-04-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ses', models.CharField(choices=[('PRO', 'Professional Class'), ('MID', 'Middle Class'), ('WORK', 'Working Class'), ('WEL', 'Welfare Class')], max_length=4)),
                ('child_age', models.IntegerField()),
                ('corpus', models.CharField(max_length=200)),
                ('race', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('OTHER', 'Other')], max_length=5)),
            ],
        ),
    ]
