# Generated by Django 3.0.6 on 2021-04-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='url',
            field=models.URLField(default='example.html'),
        ),
    ]
