# Generated by Django 3.0.6 on 2021-04-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childes', '0002_transcript_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='child_gender',
            field=models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='MALE', max_length=6),
        ),
    ]
