# Generated by Django 3.0.6 on 2021-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childes', '0003_transcript_child_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='freq_ttr',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='mlu_morphs',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='mlu_utts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transcript',
            name='mlu_words',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='percent_adjs',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='percent_adv',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='percent_nouns',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='percent_prep',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='percent_verbs',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='tot_utts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='child_age',
            field=models.CharField(max_length=10),
        ),
    ]
