# Generated by Django 3.0.6 on 2021-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childes', '0004_auto_20210412_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='freq_ttr_mot',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='mlu_morphs_mot',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='mlu_utts_mot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transcript',
            name='mlu_words_mot',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='percent_adjs_mot',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='percent_adv_mot',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='percent_nouns_mot',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='percent_prep_mot',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='percent_verbs_mot',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='transcript',
            name='tot_utts_mot',
            field=models.IntegerField(default=0),
        ),
    ]
