# Generated by Django 3.0.6 on 2021-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childes', '0006_auto_20210412_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='child_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='MALE', max_length=6),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='race',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Other', 'Other')], max_length=5),
        ),
    ]
